.TH GOFISH "5" "August 2002" "" "GoFish"
.SH NAME
gofish.conf \- the configuration file for the GoFish gopher server
.SH DESCRIPTION
.PP
This describes the configuration file for the GoFish gopher
server. GoFish does not need a configuration file to run. The
configuration file adds flexibility for either binary distributions or
running two gopher servers on seperate ports and directories.
.PP
This file is also read by the
.B mkcache
program to get the root, hostname, and port entries.
.SH FILE FORMAT
.PP
The GoFish configuration file is a simple ascii text file with option
= data pairs. All lines not starting in an alphabetic (a\-z) character
are considered comments. All options are case sensitive.
.PP
The example in the example section shows the options with
their default values (which may be changed at compile time).
.SH OPTIONS
.TP
\fBroot\fR
the root of the server directory.
.TP
\fBlogfile\fR
the file to log GoFish hits in
.TP
\fBpidfile\fR
where to put the pidfile at runtime
\fBtmpdir\fR
directory to put temporary files in. Relative to root-dir.
.TP
\fBmimefile\fR
the location of the Apache style mime.types file
.TP
\fBhost\fR
host name
.TP
\fBlisten-address\fR
address to listen on.
.TP
\fBport\fR
what port number to listen on. 70 is the gopher port
.TP
\fBuser\fR
the username of the gopher user
.TP
\fBuid, gid\fR
the numeric user and group ids of the gopher user
.TP
\fBvirtual_hosts\fR
if set to 1, GoFish will support virtual hosts
.TP
\fBcombined_log\fR
If set to 1, GoFish will use combined log format.
Else, it defaults to common log format.
Note that combined log format has no real meaning for gopher.
.TP
\fBno_local\fR
if set to 1, GoFish will not log accesses from local
machines. Local machines are defined as 192.168.x.x and 127.0.0.1.
\fBpreprocess_cache\fR
if set to 1 will dynamically process the .cache file to add host
and port if necessary.
.SH EXAMPLE
.nf
# GoFish Gopher Server configuration file
root = /var/gopher
logfile = /var/log/gopherd
pidfile = /var/run/gopherd.pid
port = 70
uid = 13
gid = 30
no_local = 1
.fi
.SH "SEE ALSO"
.BR gofish (1),
.BR mkcache (1)
.SH AUTHOR
Written by Sean MacLennan
.SH "REPORTING BUGS"
Report bugs to <headgopher@seanm.ca>.
.SH COPYRIGHT
Copyright \(co 2002-2008 Sean MacLennan
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
