apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-pod
  ports:
    - port: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-pod
          image: microtiling/api
          imagePullPolicy: Always
          env:
            - name: A_PI_ADDRESS
              value: "api-service"
---
apiVersion: v1
kind: Service
metadata:
  name: a-pi-service
spec:
  selector:
    app: a-pi
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-pi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a-pi
  template:
    metadata:
      labels:
        app: a-pi
    spec:
      containers:
        - name: a-pi-pod
          image: microtiling/a-pi
          imagePullPolicy: Always
