DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS segment;

CREATE TABLE job (
	id TEXT PRIMARY KEY,
	digits INTEGER NOT NULL
);

CREATE TABLE segment (
	job_id TEXT NOT NULL,
	x1 INTEGER NOT NULL,
	y1 INTEGER NOT NULL,
	x2 INTEGER NOT NULL,
	y2 INTEGER NOT NULL,
	FOREIGN KEY (job_id) REFERENCES job (id)
);
