CREATE TABLE IF NOT EXISTS jobs (
	id TEXT PRIMARY KEY,
	state INTEGER NOT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ensicoin (
	id TEXT NOT NULL,
	address TEXT NOT NULL,
	FOREIGN KEY (id) REFERENCES jobs (id)
);

CREATE TABLE IF NOT EXISTS result (
	id TEXT NOT NULL,
	segments TEXT NOT NULL,
	FOREIGN KEY (id) REFERENCES jobs (id)
);
