DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS ensicoin;
DROP TABLE IF EXISTS result;

CREATE TABLE jobs (
	id TEXT PRIMARY KEY,
	state INTEGER NOT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ensicoin (
	id TEXT NOT NULL,
	address TEXT NOT NULL,
	FOREIGN KEY (id) REFERENCES jobs (id)
);

CREATE TABLE result (
	id TEXT NOT NULL,
	segments TEXT NOT NULL,
	FOREIGN KEY (id) REFERENCES jobs (id)
);
